language:
  - node.js
node_js:
  - stable
  - lts/*
# rebuild the node_modules directory only if the yarn.lock changes
cache:
  directories:
    - node_modules
branches:
  - main
  - dev
  - master
notifications:
  email:
    recipients:
      - hincubator@gmail.com
    on_success: change
    on_failure: always
before_install:
  - yarn global add codecov
install:
  - yarn --frozen-lockfile

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn run test:coverage:ci:codecov
          - npx semantic-release
        after_success:
          - bash <(curl -s https://codecov.io/bash)
