language: node.js
node_js:
  - stable
  - lts/*
# rebuild the node_modules directory only if the yarn.lock changes
cache:
  directories:
    - node_modules
branches:
  - main
  - master
  - dev
notifications:
  email:
    recipients:
      - hincubator@gmail.com
    on_success: change
    on_failure: always

jobs:
  include:
    - stage: install dependeincies
      before_install: yarn global add codecov
      install: yarn --frozen-lockfile
      skip_cleanup: true
    - stage: test
      script: yarn test:coverage:ci:codecov
    - stage: release
      before_deploy:
        - yarn add global netlify-cli
        - yarn build
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
          - netlify deploy -s $NETLIFY_SITE_ID -a $NETLIFY_AUTH_TOKEN -p -d ./build
        if: branch = master

after_success:
  - bash <(curl -s https://codecov.io/bash)
