language: node_js
node_js:
  - stable
  - lts/*
os:
  - linux
# rebuild the node_modules directory only if the yarn.lock changes
cache:
  yarn: true
  directories:
    - node_modules
branches:
  - main
  - master
  - dev
notifications:
  email:
    recipients:
      - hincubator@gmail.com
    on_success: change
    on_failure: always

jobs:
  include:
    - stage: install dependeincies
      install: yarn --frozen-lockfile
      cleanup: true
    - stage: test
      script: yarn test:coverage:ci:codecov
      cleanup: true
    - stage: release
      before_deploy:
        - yarn add global netlify-cli
        - yarn build
      deploy:
        provider: script
        cleanup: true
        script:
          - netlify deploy -s $NETLIFY_SITE_ID -a $NETLIFY_AUTH_TOKEN -p -d ./build
          - npx semantic-release
        on:
          branch:
            - master
            - main

after_success:
  - bash <(curl -s https://codecov.io/bash)
